- src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
이슈링크(url): 
- 웹소켓 연결 종료 코드인 `CloseStatus`를 `afterConnectionClosed` 에 추가
없음
> Chore: 웹소켓 연결 관련 로그 구체화

- src/main/java/org/cotato/csquiz/common/config/SwaggerConfig.java
이슈링크(url): 
- 테스트 서버에 배포된 스웨거 요청 url (서버 아이템)을 추가함
> Chore: 스웨거에 테스트 서버 url 추가

- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
* chore: 기수 목록, 세션 목록 API 권한 허용
* chore: 기수 목록, 세션 목록 API 권한 허용
이슈링크(url):
> Release: API 권한 설정 변경

- src/main/java/org/cotato/csquiz/domain/generation/enums/DevTalk.java
> Release: 데브토크 상수 오류 수정

- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/SessionListResponse.java
- src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- session_title
- 길이 100자 제한
이슈링크(url):
> Release: 세션 테이블 제목 컬럼 추가

- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/37
- 세션 수정 API 내용 수정
> Feature: 세션 제목 수정 기능 구현

- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> Release: 세션 제목 수정 기능 구현 

- .github/workflows/deploy.yml
- .github/workflows/release.yml
운영 서버에서 이메일 인증이 보내지지 않는 오류 발생
이슈링크(url): 
- Github Actions 내의 환경 변수 주입 시점을 변경
> Hotfix: email 인증 변수 주입 시점 변경

- src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/51
- 새로운 소켓 연결 요청이 올 때 기존 연결을 명확하게 제거
- 별도의 Custom Error Code 4001 적용
> Feature: 소켓 연결 시 기존 세션 종료 기능 구현

- src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
> Release: 소켓 연결 시 기존 세션 종료 기능 구현 

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/UpdatePhoneNumberRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/Member.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
이슈링크(url): #48 
- 회원 전화번호 수정  로직 구현
>  Feature: 회원 전화번호 수정  로직 구현

- src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java
이슈링크(url): #22 
- 세션 업데이트 API 요청에 사진이 삭제됨에 따라 컨텐츠 타입 수정
>  Feature: 세션 업데이트 컨텐츠 타입 수정

- src/main/java/org/cotato/csquiz/common/config/SwaggerConfig.java
> Chore: QA 도메인 스웨거 설정 추가

- src/main/java/org/cotato/csquiz/common/config/SwaggerConfig.java
> [Release]: V2.20240717.02

- src/main/java/org/cotato/csquiz/common/config/CorsConfig.java
- src/main/java/org/cotato/csquiz/common/config/SwaggerConfig.java
> Chore: QA 도메인 CORS 설정 추가

- src/main/java/org/cotato/csquiz/common/config/CorsConfig.java
* chore: add swagger qa server item
* chore: QA서버 CORS 설정 추가
이슈링크(url):
> [Release]: QA 도메인 CORS 설정 추가 

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/cache/EmailRedisRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/cache/EmailType.java
- src/main/java/org/cotato/csquiz/domain/auth/cache/VerificationCodeRedisRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/EmailType.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/EmailVerificationService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/ValidateService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/70
- 현재 운영 중인 서버에서의 문제 여부
- 검증이 적절히 이루어졌는지 여부
- 외부: 비밀번호 변경과 내부 비밀번호 변경 로직이 동일해도 괜찮은지
> Feature: 이메일 인증 시 인증 요청 이메일 확인 기능 구현

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/common/config/CorsConfig.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/cache/EmailRedisRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/cache/VerificationCodeRedisRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/EmailType.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/EmailVerificationService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/ValidateService.java
> [Release] : 회원 인증 시 이메일 확인 로직 배포

- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): #47 
- 순서 유효검사 시 검증 기능 변경
> Fix: 세션 사진 순서 변경 기능 오류 수정

- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- 순서 유효검사 시 검증 기능 변경
이슈링크(url):
> [Release]: 세션 사진 순서 변경 기능 오류 수정

- src/main/java/org/cotato/csquiz/domain/attendance/embedded/Location.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/Attendance.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceType.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
이슈링크(url): 
Attendance
```SQL
create table attendance
(
attendance_id bigint auto_increment
primary key,
created_at    datetime(6) null,
modified_at   datetime(6) null,
end_time      datetime(6) not null,
latitude      double      null,
longitude     double      null,
session_id    bigint      not null,
start_time    datetime(6) not null,
constraint UK_rforve23msxifodqbiyshx31
unique (session_id)
);
```
AttendanceRecord
```SQL
create table attendance_record
(
attendance_record_id bigint auto_increment
primary key,
created_at           datetime(6)  null,
modified_at          datetime(6)  null,
attendance_type      varchar(255) not null,
location_accuracy    double       null,
member_id            bigint       not null,
attendance_id        bigint       null,
constraint …
```
> Feature: 출석 관련 테이블 생성 및 세션 테이블 필드 추가

- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
이슈링크(url): 
- 세션 장소명 컬럼명 변경
session table
```SQL
ALTER TABLE session
RENAME COLUMN session_place_title TO session_place_name;
```
> Refactor: 세션 장소명 컬럼명 변경

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceDeadLineDto.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/constant/DeadLineConstants.java
- src/main/java/org/cotato/csquiz/domain/attendance/constant/DeadLineUtil.java
- src/main/java/org/cotato/csquiz/domain/attendance/embedded/Location.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): 
- 중첩 레코드 삭제
- 출석 마감기한 컴팩트 생성자 설정
> Fix: 세션 추가 양식 변경을 통한 역직렬화 문제 해결

- src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
이슈링크(url): 
- 기수 목록 반환 API의 반환 시 기수 번호 기준으로 정렬
> Refactor: 기수 목록 조회 시 기수 번호 기준 정렬

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/repository/AttendanceRecordRepository.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OnlineAttendClient.java
- src/main/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtil.java
- src/test/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtilTest.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/pull/87#discussion_r1708507435
> Feature: 출결 마감 시간 수정에 따른 기존 출결 기록 변화

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceStatistic.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendanceRecordsResponse.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceOpenStatus.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceResult.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/DeadLine.java
- src/main/java/org/cotato/csquiz/domain/attendance/repository/AttendanceRecordRepository.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OnlineAttendClient.java
- src/main/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtil.java
- src/test/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtilTest.java
> Feature: 멤버의 기수별 출결 목록 반환 기능 구현

- src/main/java/org/cotato/csquiz/api/auth/controller/AuthController.java
- src/main/java/org/cotato/csquiz/api/auth/dto/JoinResponse.java
- src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java
- src/main/java/org/cotato/csquiz/api/policy/dto/PoliciesResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
> Feature: 회원 가입 성공 시 회원 PK 반환 및 필수 정책 반환 API 구현

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceStatistic.java
- src/main/java/org/cotato/csquiz/api/socket/controller/SocketController.java
- src/main/java/org/cotato/csquiz/api/socket/dto/EducationOpenRequest.java
- src/main/java/org/cotato/csquiz/common/SchedulerService.java
- src/main/java/org/cotato/csquiz/common/config/WebSocketConfig.java
- src/main/java/org/cotato/csquiz/common/websocket/HandshakeInterceptor.java
- src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/education/repository/QuizRepository.java
- src/main/java/org/cotato/csquiz/domain/education/service/EducationService.java
- src/main/java/org/cotato/csquiz/domain/education/service/QuizSolveService.java
- src/main/java/org/cotato/csquiz/domain/education/service/RecordService.java
- src/main/java/org/cotato/csquiz/domain/education/service/SocketService.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Project.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectImage.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectMember.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/ProjectImageType.java
```SQL
create table project
(
project_id           bigint auto_increment
primary key,
behance_url          varchar(255) null,
generation_id        bigint       not null,
github_url           varchar(255) null,
project_introduction varchar(255) null,
project_name         varchar(255) null,
project_url          varchar(255) null
);
-- auto-generated definition
create table project_image
(
project_image_id   bigint auto_increment
primary key,
project_id         bigint       not null,
project_image_type varchar(255) null,
file_name          varchar(255) null,
folder_name        varchar(255) null,
url                varchar(255) null
);
-- auto-generated definition
create table project_member
(
project_member_id bigint auto_increment
primary key,
position          varchar(255) null,
name …
```
> [Release] 2024.08.15.01

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java
- src/main/java/org/cotato/csquiz/api/project/controller/ProjectController.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectDetailResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectImageInfoResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectMemberInfoResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectSummaryResponse.java
- src/main/java/org/cotato/csquiz/common/S3/S3Uploader.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java
- src/main/java/org/cotato/csquiz/common/util/FileUtil.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectImageRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectMemberRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
> [Release] 2024.08.18.01

- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java
> Refactor: 스웨거 응답 필드 nullable 설정 변경

- src/main/java/org/cotato/csquiz/common/util/FileUtil.java
이슈링크(url): 
- 대문자 파일 확장자 이미지 리스트에 추가
> Feature: 대문자 파일 확장자 이미지 리스트에 추가

- src/main/java/org/cotato/csquiz/common/util/FileUtil.java
이슈링크(url): 
* feat: 대문자 파일 확장자 이미지 리스트에 추가
> [Release] 2024.08.19.02

- src/main/java/org/cotato/csquiz/api/project/dto/ProjectMemberInfoResponse.java
> [Release] V2.2024.08.20.03

- src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> [Release] V2 2024.08.21.02

- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
> Chore: 정확도 관련 로그 추가

- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
> Chore: 정확도 관련 로그 추가 (#122)

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/OfflineAttendanceRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
> Feature: 출결 입력 로직 검증 로직 추가

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/OfflineAttendanceRequest.java
* chore: 정확도 관련 로그 추가
* feat: 출결 입력 request 검증
이슈링크(url):
> [Release] V2.2024.08.22.02

- src/main/java/org/cotato/csquiz/api/project/controller/ProjectController.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectImageRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectImageResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectImageRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectMemberRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectSummaryResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectImage.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectMember.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectImageService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectMemberService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
> Feature: 프로젝트 등록 API 구현

- src/main/java/org/cotato/csquiz/api/project/controller/ProjectController.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectImageRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectImageResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectResponse.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectImageRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectMemberRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectSummaryResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectImage.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectMember.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectImageService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectMemberService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
* feat: 프로젝트 등록 API 구현
* refactor: 프로젝트 상세 정보 반환 값 수정
* fix: 사진 업로드를 위한 request 타입 변경
* feat: 로고 이미지와 썸네일 이미지 생성자 분리
* refactor: 로고와 썸네일 이미지만 업로드
* refactor: 프로젝트 추가와 사진 추가 분리
* feat: 프로젝트 이미지 추가 별도 구현
* refactor: api endpoint 오타 수정
* feat: security 권한 추가
* feat: 이벤트 구독 관련 요청 허용
이슈링크(url):
> [Release]: V2.2024.08.23.01

- src/main/java/org/cotato/csquiz/api/admin/dto/MemberInfoResponse.java
이슈링크(url): 
- 멤버 정보 반환 시 포지션 추가
> Feature: 멤버 정보 반환 시 포지션 추가

- src/main/java/org/cotato/csquiz/api/admin/dto/MemberInfoResponse.java
> [Main] V2.2024.08.23.03

- src/main/java/org/cotato/csquiz/domain/auth/entity/MemberPolicy.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/146
> Fix: 동의한 정책이 보이지 않는 에러 해결

- src/main/java/org/cotato/csquiz/domain/auth/entity/MemberPolicy.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
* feat: 회원 정책과 기록 연관관계 제거
* fix: 동의한 회원 정책을 반환하지 않는 오류 수정
* refactor: 정책 동의 메서드 수정
이슈링크(url):
> [Release] V2.2024.09.06.01

- build.gradle
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/common/s3/S3Uploader.java
- src/main/java/org/cotato/csquiz/common/util/FileUtil.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectImageService.java
> Feature: 프로젝트 이미지 업로드 시 webp 변환

- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java
- src/main/java/org/cotato/csquiz/api/project/controller/ProjectController.java
- src/main/java/org/cotato/csquiz/api/project/dto/CreateProjectImageRequest.java
- src/main/java/org/cotato/csquiz/api/project/dto/ProjectImageInfoResponse.java
- src/main/java/org/cotato/csquiz/common/schedule/SchedulerService.java
- src/main/java/org/cotato/csquiz/common/util/TimeUtil.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceType.java
- src/main/java/org/cotato/csquiz/domain/attendance/repository/AttendanceRecordRepository.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectImage.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectImageService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> [Release] V2.2024.09.18.01

- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
> Fix: 킹킹 멤버, 우승자 반환 API 권한 설정 변경

- .github/workflows/deploy.yml
- .github/workflows/release.yml
* [CSQ-2] feat: stage 환경 디스코드 환경 변수 추가
* [CSQ-2] feat: prod 환경 디스코드 환경 변수 추가
[CSQ-2]: https://youthing.atlassian.net/browse/CSQ-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSQ-2]: https://youthing.atlassian.net/browse/CSQ-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Release] V2.2024.10.03.02

- src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/GenerationServiceTest.java
이슈링크(url): 
- 현재 날짜를 기준으로 기수 반환하는 기능 구현
> [COT-3] Feature: 현재 날짜를 기준으로 기수를 반환하는 기능 구현

- src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/GenerationServiceTest.java
> [Release] V2.2024.10.07.01

- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
이슈링크(url): 
- 관리자가 모든 활동 부원의 출결 기록을 볼 수 있게 수정
> [COT-16] Feature: 관리자의 활동 부원 출결 기록 조회 기능 추가

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java
- src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java
- src/main/java/org/cotato/csquiz/api/session/dto/SessionListImageInfoResponse.java
- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> [COT-21] Feature: 세션 단건 조회 API 구현

- src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRole.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
```sql
create table generation_member
(
generation_member_id bigint auto_increment
primary key,
created_at           datetime(6)                   null,
modified_at          datetime(6)                   null,
role                 varchar(255) default 'MEMBER' null,
generation_id        bigint                        not null,
member_id            bigint                        not null,
constraint FK3qi5j0lxivmvw2akuysmbqb6p
foreign key (member_id) references member (member_id),
constraint FK4jkpvmxl6o99kdfwumiqlrk3l
foreign key (generation_id) references generation (generation_id)
);
```
> [COT-27] Feature: 기수별 멤버 테이블 추가

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRecordRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceRecordResult.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRole.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
> [Release] V2.2024.10.27.01

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRecordRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceRecordResult.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRole.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
> [Release] V2.2024.10.27.02

- build.gradle
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
- src/main/java/org/cotato/csquiz/migration/MigrationJob.java
- src/main/java/org/cotato/csquiz/migration/MigrationLog.java
- src/main/java/org/cotato/csquiz/migration/MigrationLogRepository.java
- src/main/java/org/cotato/csquiz/migration/MigrationRunner.java
- src/main/java/org/cotato/csquiz/migration/generation/CurrentGenerationMemberMigration.java
GeneartionMember 테이블이 생성됨에 따라 현재 활동 중인 부원을 마이그레이션한다.
```sql
-- auto-generated definition
create table migration_log
(
id             bigint auto_increment
primary key,
created_at     datetime(6)  null,
migration_name varchar(255) null,
constraint UK_skv0osxdibwnrl8115n47uwo1
unique (migration_name)
);
```
> [COT-28] Feature: 현재 활동 기수 데이터 마이그레이션

- build.gradle
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
- src/main/java/org/cotato/csquiz/migration/MigrationJob.java
- src/main/java/org/cotato/csquiz/migration/MigrationLog.java
- src/main/java/org/cotato/csquiz/migration/MigrationLogRepository.java
- src/main/java/org/cotato/csquiz/migration/MigrationRunner.java
- src/main/java/org/cotato/csquiz/migration/generation/CurrentGenerationMemberMigration.java
* chore: add lombok to test
* feat: add data migration log table
* feat: add data migration runner
* feat: add current generation migration runner
* fix: change jpa method parameter
* refactor: change to stream
이슈링크(url):
> [Release] V2.2024.10.29.01

- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/MemberReader.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/GenerationReader.java
- src/test/java/org/cotato/csquiz/domain/auth/service/component/MemberReaderTest.java
이슈링크(url): 
- Stream -> Map을 하는 과정에서 N + 1 쿼리를 어떻게 줄일 것인가
> [COT-29] Feature: 현재 활동중인 부원 조회 로직 변경

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/MemberReader.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/GenerationReader.java
- src/test/java/org/cotato/csquiz/domain/auth/service/component/MemberReaderTest.java
> [Release] V2.2024.10.30.01

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceDeadLineDto.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceTimeResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtil.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- src/test/java/org/cotato/csquiz/domain/attendance/util/AttendanceUtilTest.java
이슈링크(url): 
- 출결 시간 반환 DTO 타입 변경
- AddSession, UpdateSession 시 출결 마감, 지각 마감 시간 타입 변경
- LocalTime -> LocalDateTime
> [COT-61] Feature: 출결 시간 타입 변경

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceWithSessionResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendancesResponse.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/component/AttendanceReader.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
- src/main/java/org/cotato/csquiz/migration/MigrationRunner.java
- 출석 단건 조회 API 신설
- DTO 클래스 네이밍 단순화
- AttendanceResponse -> AttendanceWithSessionResponse
- AttendacneResponse: 출석에 대한 정보만을 담고 있음
> [COT-62] Feature: 출석 단건 조회 API

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceParams.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/OfflineAttendanceRequest.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/OnlineAttendanceRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceResult.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/OfflineAttendClient.java
이슈링크(url): 
- AttendanceResult 설명 변경
- 오프라인 출석 시 attendanceResult 값도 변경하게 변경
> [COT-72] Fix: 출결 결과 ENUM 설명 오류 수정

- src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionResponse.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- 세션 추가 시 대면, 비대면 여부를 선택 가능
마이그레이션 이전
```sql
ALTER TABLE session
ADD COLUMN type VARCHAR(255) NULL;
update session set type = 'ALL' where type is null;
ALTER TABLE session
MODIFY COLUMN type VARCHAR(255) NOT NULL;
```
> [COT-63] Feature: 세션 추가 시 출결 옵션을 선택할 수 있다.

- src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/DeleteGenerationMemberRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/GenerationMemberReader.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
이슈링크(url): 
- 기수별 활동 부원 삭제 API
> [COT-90] Feature: 기수별 활동 부원 삭제

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/RequestAttendanceService.java
resolve: https://github.com/IT-Cotato/COTATO-BE/issues/204
해당 pr https://github.com/IT-Cotato/COTATO-BE/pull/221 과 의존성이 있습니다.
> [COT-91] Feature: 세션 타입에 따른 출결 입력 제한

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceRecordController.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceTimeResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceWithSessionResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendancesResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendanceRecordsResponse.java
- src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRecordRequest.java
- src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/CreateGenerationMemberRequest.java
- src/main/java/org/cotato/csquiz/api/member/dto/DeleteGenerationMemberRequest.java
- src/main/java/org/cotato/csquiz/api/member/dto/UpdateGenerationMemberRoleRequest.java
- src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java
- src/main/java/org/cotato/csquiz/api/session/dto/AddSessionResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/RequestAttendanceService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/GenerationMemberReader.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/MemberReader.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
```SQL
ALTER TABLE session
ADD COLUMN type VARCHAR(255) NULL;
update session set type = 'ALL' where type is null;
ALTER TABLE session
MODIFY COLUMN type VARCHAR(255) NOT NULL;
> [Release] V2.2024.12.03.01

- src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/GenerationMemberInfo.java
- src/main/java/org/cotato/csquiz/api/member/dto/GenerationMemberInfoResponse.java
- src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/GenerationMemberReader.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
> [COT-65] Feature: 기수별 활동 멤버 목록 반환 API 

- src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java
- src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/entity/Attendance.java
- src/main/java/org/cotato/csquiz/domain/generation/embedded/SessionContents.java
- src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-104
- 세션 수정 시 출결 옵션 선택 가능
- 왜인지 모르겠으나 세션 수정 시 출결 시간 변경 코드가 없었음 추가 수정
> [COT-104] Feature: 세션 수정 시 출결 옵션 선택 가능

- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
세션 단건 조회에도 출결 타입을 반환하자
하면서 스웨거 필드도 내려주자
> [COT-113] Feature: 세션 단건 조회에 출결 타입 반환

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
Reverts IT-Cotato/COTATO-BE#229
> Revert "[COT-108] Refactor: AttendanceAdminService 추상화"

- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
Reverts IT-Cotato/COTATO-BE#233
> Revert "[COT-113] Feature: 세션 단건 조회에 출결 타입 반환"

- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
> [COT-113] Feature: 세션 단건 조회 시 출결 필드 반환

- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
> [COT-113] Feature: 세션 단건 조회 시 출결 옵션

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> [COT-108] Refactor: AttendanceAdminService 추상화

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java
- src/main/java/org/cotato/csquiz/api/session/dto/SessionWithAttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
> [Release] V2.2024.12.11.02

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
base branch 가 https://github.com/IT-Cotato/COTATO-BE/pull/229 입니다.
> [COT-106] Feature: 출결 기록 수정 시 세션 타입에 맞는 기록 수정만 가능하다.

- src/main/java/org/cotato/csquiz/domain/attendance/repository/AttendanceRepository.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/component/AttendanceReader.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/SessionRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
이슈링크(url): 
- session 찾을 시 비관적 X-Lock 추가
- 출석 찾을 시 비관적 X-Lock 추가
> [COT-89] Feature: 세션 수정 시 비관적 X-Lock 생성

- src/main/java/org/cotato/csquiz/api/quiz/controller/RandomQuizController.java
- src/main/java/org/cotato/csquiz/api/quiz/dto/RandomQuizReplyRequest.java
- src/main/java/org/cotato/csquiz/api/quiz/dto/RandomQuizReplyResponse.java
- src/main/java/org/cotato/csquiz/api/record/dto/ReplyResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/domain/education/entity/RandomQuiz.java
- src/main/java/org/cotato/csquiz/domain/education/service/RandomQuizService.java
- src/main/java/org/cotato/csquiz/domain/education/service/component/RandomQuizReader.java
외부인이 튜토리얼 버전 CS 퀴즈를 체험하기 위함
- 랜덤 문제 정보 반환 API
- 문제 제출 -> 결과 받기 API
resolve: #247
> [COT-118] Feature: 랜덤 퀴즈 제출 API 구현

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-126&sprints=8
> [COT-126] Hotfix: 출결 단건 조회 시 세션 타이틀 추가

- src/main/java/org/cotato/csquiz/api/attendance/dto/OfflineAttendanceRequest.java
- src/main/java/org/cotato/csquiz/domain/attendance/embedded/Location.java
> [COT-144] Hotfix: 대면 출결 시 위치값이 Null인 경우 에러를 발생한다.

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/service/ValidateService.java
기존 전화번호 검증 관련 에러는 INVALID_PHONE_NUMBER로 통일되어 내려가고 있다.
길이 문제인지, 숫자 형식 문제인지, 010 시작을 안하는지 구분이 필요하다.
에러 케이스를 추가하자.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-158&sprints=9
> [COT-157] Feature: 전화번호 검증 에러 다양화

- .gitignore
querydsl QEntity 생성 위치 gitignore 설정
QEntity 생성 위치인 `src/main/generated/` 를 gitignore에 설정
> [COT-162] Chore: querydsl gitignore 설정

- src/main/java/org/cotato/csquiz/api/education/controller/EducationController.java
- src/main/java/org/cotato/csquiz/api/education/dto/EducationCountResponse.java
- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/domain/education/service/EducationService.java
CS퀴즈탭 외부인 페이지 1번에 문제 및 교육 횟수가 추가되어야한다.
API 만들자.
resolve: https://youthing.atlassian.net/browse/COT-142
> [COT-142] Feature: 교육 및 문제 수 반환 API

- src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/DeleteGenerationMemberRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java
기획적으로 기수별 멤버 삭제를 단건으로 변경함에 따라 API 변경
기존 List<Long>으로 받는 방식에서 PK 하나만 받게 request 변경
> [COT-170] Feature: 기수별 멤버 삭제 단건으로 변경

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceRecordController.java
- src/main/java/org/cotato/csquiz/api/auth/controller/AuthController.java
- src/main/java/org/cotato/csquiz/api/education/controller/EducationController.java
- src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/mypage/controller/MyPageController.java
- src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java
- src/main/java/org/cotato/csquiz/api/policy/dto/FindMemberPolicyResponse.java
- src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java
- src/main/java/org/cotato/csquiz/api/socket/controller/SocketController.java
- src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
- src/main/java/org/cotato/csquiz/common/config/jwt/JwtTokenProvider.java
- src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
- src/main/java/org/cotato/csquiz/domain/education/service/MyPageService.java
- src/main/java/org/cotato/csquiz/domain/education/service/SocketService.java
- COT-121 (#252 )
- COT-153 (#263 )
> [Main] V2.2025.01.22.01

- src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java
https://github.com/IT-Cotato/COTATO-BE/pull/279 에서 문제를 해결하지 못함
이유는 SecurityConfig에서 여전히 검증하고 있었기 때문
- white-list 처리
> [COT-178] Hotfix: 세션과 연결된 교육 할당 API 권한 추가 해결

- src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceExcelController.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/attendance/repository/AttendanceRepository.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/component/AttendanceReader.java
- src/main/java/org/cotato/csquiz/domain/attendance/util/AttendanceExcelUtil.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/SessionRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
출석별로 출결 기록을 다운로드 하고 싶다.
하나의 시트에 다운로드 하고 싶다.
https://docs.google.com/spreadsheets/d/16TxUfSKBCfJBp-8jNLiL7Jrdt4bpWmi-p5vg8XZtvsg/edit?gid=1346858463#gid=1346858463
구현한다.
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-164&sprints=11
> [COT-164] Feature: 출석별 엑셀 다운로드 API

- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
> [COT-189] Feature: 엑셀 추출 메서드 트랜잭션 설정

- src/main/java/org/cotato/csquiz/common/config/CorsConfig.java
Content-Disposition 헤더가 CORS설정에 의해 노출되지 않고 있음
노출한다.
> [COT-190] Feature: content-disposition 헤더 노출

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/DeactivateRequest.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/Member.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/MemberLeavingRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/MemberStatus.java
- src/main/java/org/cotato/csquiz/domain/auth/repository/MemberLeavingRequestRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/PolicyReader.java
부원 탈퇴 요청 API를 구현한다.
요청 시 30일간 데이터를 보관해야한다.
우선 요청 처리 API 와 요청만 기록
추후에 30일 이후 자동삭제 추가 구현 예정
```sql
CREATE TABLE member_leaving_request (
id BIGINT NOT NULL AUTO_INCREMENT,
created_at DATETIME(6),
modified_at DATETIME(6),
deleted_at DATETIME(6),
is_reactivated BIT NOT NULL,
requested_at DATETIME(6) NOT NULL,
member_id BIGINT,
PRIMARY KEY (id),
CONSTRAINT FK5xpg46h0m6voxkkdv0i9orbbk FOREIGN KEY (member_id) REFERENCES member (member_id)
) ENGINE=InnoDB;
```
> [COT-181] Feature: 부원 탈퇴 요청 처리 API 구현

- src/main/java/org/cotato/csquiz/api/admin/controller/AdminController.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/MemberResponse.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
status 필드에 따른 부원 목록을 조회한다.
status에 따른 조회 구현
> [COT-193] Feature: 상태에 따른 부원 조회 API 

- src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
현재 기수 추가, 수정 시 기간이 겹치는지 확인하는 로직이 없다.
추가해주자
https://youthing.atlassian.net/browse/COT-195
> [COT-195] Feature: 기수 추가, 수정 시 기간 겹침 여부 확인

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/MemberLeavingRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/repository/MemberLeavingRequestRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/component/MemberLeavingRequestReader.java
- src/test/java/org/cotato/csquiz/domain/auth/service/MemberServiceTest.java
탈퇴 요청 후 비활성화 처리된 부원이 로그인하면 재활성화 시도가 가능하다.
재활성화 API 구현
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-196&sprints=5
코드 참조
> [COT-196] Feature: 비활성화 처리된 부원의 재활성화 요청

- src/main/java/org/cotato/csquiz/api/admin/controller/AdminController.java
- src/main/java/org/cotato/csquiz/api/admin/dto/MemberApproveRequest.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/Member.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/AdminMemberServiceTest.java
AdminController에서 진행되는 부원 가입 승인 거절 엔드포인트가 부적절하다.
맞춰서 수정하자.
코드 참조
> [COT-194] Feature: 부원 가입 승인/거절 API 변경

- .github/workflows/test.yml
현재 release, main 브랜치에 PR을 올릴 때 컴파일 확인을 하지 않는다.
하자
> [COT-199] Chore: release, main 브랜치에 PR 시 컴파일 설정

- src/main/java/org/cotato/csquiz/api/admin/controller/AdminController.java
- src/main/java/org/cotato/csquiz/api/admin/dto/UpdateMemberRoleRequest.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/AdminMemberServiceTest.java
부원 역할 변경 API 엔드포인트를 변경한다.
base branch가 https://github.com/IT-Cotato/COTATO-BE/pull/294입니다.
한다.
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-197&sprints=5
코드
> [COT-197] Feature: 부원 역할 변경 API 엔드포인트 변경

- src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java
- src/main/java/org/cotato/csquiz/domain/auth/entity/Policy.java
- src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/PolicyServiceTest.java
회원이 체크하지 않은 정책 조회 API 가 이상하게 사용되고 있다.
(지금 생각해보면 엔드포인트도 이상하다.)
엔드포인트 및 파라미터를 추가해서 구체적으로 의미를 전달한다.
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-202&sprints=5
> [COT-202] Feature: 회원이 체크하지 않은 정책 조회 API

- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/SessionServiceTest.java
현재 출석 기록 수정 시 세션 시간을 수정할 수 있다.
수정 못하게 변경하자
https://youthing.atlassian.net/browse/COT-200
> [COT-200] Feature: 출석 기록 존재 시 세션 시간 변경 불가

- src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceWithSessionResponse.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
출결 목록 반환 시 출석 진행 여부 반환이 되고 있지 않다.
반환 추가한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-203&sprints=11
> [COT-203] Feature: 출결 목록 반환 시 시작 여부 반환

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/common/poi/ExcelWriter.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceOpenStatus.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
출결 예정인 세션의 출결 기록은 다운로드 시 다음과 같이 처리해야한다.
- 기수별 출석 : 제외
- 출결 선택 : 에러
> [COT-204] Feature: 출결 예정인 세션은 엑셀 다운로드에서 제외한다.

- src/main/java/org/cotato/csquiz/api/admin/controller/AdminController.java
- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/AdminMemberServiceTest.java
아래 2가지 작업을 통해 부원 역할을 변경하는 API의 엔드포인트가 명확하지 않다.
- 부원들을 OM으로 전환
- OM을 부원으로 전환
이동한다.
코드 참조
> [COT-198] Feature: 부원 상태 변경 API 

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- 멤버 상태 별 필터링 API 엔드포인트와 겹침
- 
- "/member" -> "member/addable 로 수정
https://youthing.atlassian.net/browse/COT-210
> [COT-210] Feature: 기수별 멤버에 추가 가능한 멤버 API 엔드포인트 변경

- src/main/java/org/cotato/csquiz/api/admin/controller/AdminController.java
- src/main/java/org/cotato/csquiz/api/admin/dto/MemberApproveRequest.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java
신입 감자 가입 개발에 따라 일부 DTO 필드와 API를 제거한다.
> [COT-218] Feature: 삭제된 API 및 DTO 필드 제거

- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
출석별 엑셀 다운로드 시 엑셀이 다운로드 되지 않는다.
필터가 잘못 걸렸다.
해결하자
> [COT-221] Hotfix: 출석 엑셀 다운로드 시 엑셀이 다운로드 되지 않는 이슈 해결

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepository.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/MemberServiceTest.java
부원 데이터가 많아지면서 상태에 따른 부원 목록 조회 시 페이징이 필요하다.
페이징하자
> [COT-227] Feature: 상태에 따른 부원 목록 조회 API 페이징 적용

- src/main/java/org/cotato/csquiz/domain/auth/constant/EmailConstants.java
상수를 관리하는 클래스는 final class 로 사용해 의도치 않은 상속을 방지해야한다.
https://mangkyu.tistory.com/47
수정하자
> [COT-229] Refactor: 상수 상속 방지를 위한 final class 설정

- src/main/java/org/cotato/csquiz/common/config/CorsConfig.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/common/poi/ExcelWriter.java
- src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceOpenStatus.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceExcelService.java
- src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java
- src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
출결 기록 엑셀 다운로드 배포
close: https://github.com/IT-Cotato/COTATO-BE/milestone/3
> [Main] V2.2025.03.06

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/api/member/dto/AddableMembersResponse.java
- src/main/java/org/cotato/csquiz/api/member/dto/SearchedMemberInfo.java
- src/main/java/org/cotato/csquiz/api/member/dto/SearchedMembersResponse.java
- src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
> [COT-231] Feature: OM이름 검색 API 구현

- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/ProjectServiceTest.java
프로젝트 탭 정렬 시 최신 기수 기준으로 노출이 되어야한다.
정렬한다.
> [COT-235] Feature: 프로젝트 탭을 최신 순으로 정렬

- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/GenerationServiceTest.java
기수 기간 변경시 본인 기수가 겹쳐져도 예외가 발생한다.
수정하자
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-232
> [COT-232] Fix: 기수 변경 시 본인 기수가 겹치면 정상 작동하게 변경

- src/main/java/org/cotato/csquiz/domain/auth/constant/EmailConstants.java
- src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java
- src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/GenerationServiceTest.java
> [COT-232] Fix: 기수 기간 수정 시 기간 중복 문제 해결

- src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
- src/test/java/org/cotato/csquiz/domain/generation/service/ProjectServiceTest.java
> [COT-235] Feature: 프로젝트 탭 최신 순 정렬

- src/main/java/org/cotato/csquiz/common/role/RoleInterceptor.java
현재 기본적인 Controller Method를 제외하고 서버에 다른 요청이 들어올 때도 역할 체크 인터셉터를 지나간다.
이로 인해 클래스 캐스팅 에러가 발생하는 중
Controller가 아니면 인터셉터를 통과한다.
> [COT-240] Feature: 정적 리소스 핸들링 시 역할 확인 인터셉터 통과

- .github/workflows/deploy.yml
- .github/workflows/release.yml
기존 프로필 이미지 작업 시 환경 변수를 CI/CD 스크립트에 저장하지 않아 빌드 과정에서 문제가 발생함
설정한다.
> [COT-241] Chore: 프로필 이미지 변수 CI/CD 스크립트 설정

- src/main/java/org/cotato/csquiz/common/websocket/HandshakeInterceptor.java
- src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRoleGroup.java
멤버 그룹에 DEV가 추가되지 않아 웹소켓 접속이 안되는 문제 발생
수정하자
> [COT-249] Feature: 멤버그룹에 DEV 추가

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/AdminMemberServiceTest.java
현재 부원 접근 권한 관리에서 개발팀을 OM으로 전환하면 전환이 되는 상태.
되지 않아야 정상이다.
✅ 논의 필요
> [COT-246] Feature: 개발팀은 OM으로 전환하지 않는다.

- src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java
- src/test/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordServiceTest.java
https://github.com/IT-Cotato/COTATO-BE/pull/334 에서 수정 
바꾸려는 결과가 결석, 지각인 경우 허용한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-254&sprints=13
> [COT-254] Hotfix: 지각, 결석으로 기록을 변경할 수 있다

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
- src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepositoryCustom.java
- src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepositoryCustomImpl.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- src/test/java/org/cotato/csquiz/domain/auth/service/MemberServiceTest.java
OM이 늘어나면서 부원 반환 시 페이징 적용이 필요하다.
적용하자
> [COT-259] Feature: OM 검색 API 페이징 적용

- src/main/java/org/cotato/csquiz/api/recruitment/controller/RecruitmentController.java
- src/main/java/org/cotato/csquiz/api/recruitment/dto/ChangeRecruitmentInfoRequest.java
- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/domain/recruitment/entity/RecruitmentInformation.java
- src/main/java/org/cotato/csquiz/domain/recruitment/service/RecruitmentInformationService.java
모집 상태를 수정하는 API
마감기한이 지난 후 자동으로 꺼지게 스케쥴러 등록 
구현
https://youthing.atlassian.net/browse/COT-267
> [COT-267] Feature: 모집 상태 수정 API 구현

- src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java
부원 활성화 요청은 MEMBER라면 누구나 가능한 기능인데 ADMIN 제한이 있다.
제한하지 않는다.
> [COT-276] Feature: 부원 활성화 요청 시 역할 제한 제거

- src/main/java/org/cotato/csquiz/api/member/dto/ProfileInfoResponse.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
이미지 파일이 null이면 기본 이미지 반환
수정
https://youthing.atlassian.net/browse/COT-278
> [COT-278] Feature: 이미지 파일이 null이면 기본 이미지 반환

- src/main/java/org/cotato/csquiz/api/member/dto/ProfileInfoResponse.java
- src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
이미지 파일이 null이면 기본 이미지 반환
https://youthing.atlassian.net/browse/COT-278
> [Release] V2.2025.05.08.01 

- src/main/java/org/cotato/csquiz/api/recruitment/controller/RecruitmentController.java
- src/main/java/org/cotato/csquiz/api/recruitment/dto/RecruitmentNotificationLogDto.java
- src/main/java/org/cotato/csquiz/api/recruitment/dto/RecruitmentNotificationLogResponse.java
- src/main/java/org/cotato/csquiz/api/recruitment/dto/RecruitmentNotificationLogsResponse.java
- src/main/java/org/cotato/csquiz/domain/recruitment/entity/RecruitmentNotification.java
- src/main/java/org/cotato/csquiz/domain/recruitment/repository/RecruitmentNotificationEmailLogRepository.java
- src/main/java/org/cotato/csquiz/domain/recruitment/repository/RecruitmentNotificationRepository.java
- src/main/java/org/cotato/csquiz/domain/recruitment/service/RecruitmentNotificationService.java
- src/main/java/org/cotato/csquiz/domain/recruitment/service/component/RecruitmentNotificationEmailLogReader.java
- src/main/java/org/cotato/csquiz/domain/recruitment/service/component/RecruitmentNotificationReader.java
- src/test/java/org/cotato/csquiz/domain/recruitment/service/RecruitmentNotificationServiceTest.java
최근 5개의 모집 알람 전송 기록을 반환
API 구현
https://youthing.atlassian.net/browse/COT-265
> [COT-265] Feature: 모집 알람 전송 기록 반환 API

- src/main/java/org/cotato/csquiz/domain/recruitment/email/RecruitmentEmailFactory.java
디자이너 + 기획자에 요청에 따라 메일 html 수정
수정
https://youthing.atlassian.net/browse/COT-282
> [COT-282] Feature: 모집 알림 메일 디자인 수정

- src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java
> [COT-288] Chore: OPEN API 파라미터 명시

- src/main/java/org/cotato/csquiz/common/error/ErrorCode.java
- src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java
- src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
- src/test/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandlerTest.java
현재 QA에서 세션을 추가하면 403예외가 발생한다. 확인 결과 Builder를 통한 세션을 생성할 때 필드를 누락해 NPE가 발생한 것
- 오류 해결
- NPE등 예기치 못한 예외가 발생할 때 핸들 처리
> [COT-293] Fix: 세션 추가 실패 및 예기치 못한 예외 처리
