IT-Cotato/COTATO-BE

.github/workflows/deploy.yml, .github/workflows/release.yml, build.gradle, scripts/deploy.sh, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application-stage.yml, src/main/resources/application.yml
테스트 환경과 운영 환경을 분리
1. 테스트 환경
- 포트 8082
- stageJar
- application-stage.yml
2. 운영환경
- 포트 8080
- prodJar
- application-prod.yml
=> Chore: 배포자동화 및 테스트 서버 CI/CD 구축

src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/api/quiz/controller/QuizController.java, src/main/java/org/cotato/csquiz/api/socket/controller/SocketController.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java, src/main/java/org/cotato/csquiz/domain/education/cache/QuizAnswerRedisRepository.java, src/main/java/org/cotato/csquiz/domain/education/cache/ScorerExistRedisRepository.java, src/main/java/org/cotato/csquiz/domain/education/service/QuizService.java, src/main/java/org/cotato/csquiz/domain/education/service/RecordService.java, src/main/java/org/cotato/csquiz/domain/education/util/AnswerUtil.java
사용하지 않는 2가지 API를 제거함
- 비밀번호 일치 확인 (`/v1/api/member/check/password`): 해당 기능을 다른 API에서 수행하고 있음
- 정답 추가 (`/v1/api/quiz/cs-admin/add`): regrade관련 API만 사용 중임. 
- 제거한 API와 메서드를 no usage기준으로 지웠는데 남길 필요가 있을지
- 프론트 개발자와 소통 후 정답 추가 (`/v1/api/quiz/cs-admin/add`) API가 사용됨에 따라 커밋 롤백 후 추가
- 이 과정에서 캐시에 정답을 추가하는 로직을 합침
- 주관식 정답 사전 처리 관련 유틸 클래스 생성
- 정답 추가 관련 일부 메서드 이름 변경 (additional을 명시)
- 캐시에 정답을 추가하는 경우 ToCache를 통해 명시적으로 이름 변경
- 캐시 저장 시 중복 조회를 줄이고자 조회 위치 변경
- 작업 내용 한번씩 읽어주세요~
=> Refactor: 사용하지 않는 API 제거

src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java, src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java, src/main/java/org/cotato/csquiz/api/session/dto/SessionListResponse.java, src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java, src/main/java/org/cotato/csquiz/domain/generation/embedded/GenerationPeriod.java, src/main/java/org/cotato/csquiz/domain/generation/embedded/SessionContents.java, src/main/java/org/cotato/csquiz/domain/generation/entity/Generation.java, src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java, src/main/java/org/cotato/csquiz/domain/generation/enums/DevTalk.java, src/main/java/org/cotato/csquiz/domain/generation/repository/SessionRepository.java, src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java, src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/26
- 세션 데브톡 컬럼 추가
- GenerartionPeriod.java 패키지 이동 common -> domain 
- 세션 컨텐츠인 IT이슈, 네트워킹, CS교육, 데브톡을 Embedded 컬럼으로 묶는 것은 어떠한지 리뷰 바람
장점
- 한 곳에서 관리 가능
- Session.java 클래스 간소화
단점
- @AttributeOverrides릍 통한 컬럼명 재정의 필요
- 기존 GenerationPeriod과 달리 활용도가 한정적임
=> Feature: 세션 데브톡 컨텐츠 추가 및 임베디드화

src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
이슈링크(url): 
- 요구 사항이 변함에 따라 '기수 목록 조회' 및 '세션 목록 조회' API의 권한을 전역으로 설정함
- 변경 사항에 따른 다른 API 의 권한 변경 여부 확인 필요
=> Chore: 기수 목록 및 세션 목록 API 권한 허용

src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java, src/main/java/org/cotato/csquiz/api/session/dto/SessionListResponse.java, src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java, src/main/java/org/cotato/csquiz/domain/generation/entity/Session.java, src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/37
- session_title 컬럼 추가
- 길이 100자 제한
- 
- 세션 추가 API에 '제목' 컬럼을 `@NotNull`로 Validation확인한 것 인지 요망
- 수정에 따른 관련 API 사이드 이펙트 확인
=> Feature: 세션테이블 '제목' 컬럼 추가

src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java
=> Main: 소켓 연결 시 기존 세션 종료 기능 구현

src/main/java/org/cotato/csquiz/common/S3/S3Uploader.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java, src/main/java/org/cotato/csquiz/common/util/FileUtil.java
이슈링크(url): 
- 기존 UUID로 url을 만들게 됨에 따라 파일 확장자가 url에 추가되지 않은 문제 발생
- url에 파일 확장자 추가
=> Feature: 사진 저장 시 파일 확장자 추가

src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceAdminController.java, src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceDeadLineDto.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendancesResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRequest.java, src/main/java/org/cotato/csquiz/api/session/dto/AddSessionRequest.java, src/main/java/org/cotato/csquiz/domain/attendance/constant/DeadLineConstants.java, src/main/java/org/cotato/csquiz/domain/attendance/embedded/Location.java, src/main/java/org/cotato/csquiz/domain/attendance/entity/Attendance.java, src/main/java/org/cotato/csquiz/domain/attendance/enums/AttendanceOpenStatus.java, src/main/java/org/cotato/csquiz/domain/attendance/enums/DeadLine.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceAdminService.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java, src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
현재 출석과 세션은 1:1 관계임.
'출석 목록' 조회를 하다보니 '세션 제목'이라는 세션 값 조회가 필수라는 것을 느낌.
Join을 계속 하는 것이 성능적으로 괜찮을까에 대한 고민이 있음
두 테이블의 역정규화를 통해 다시 합치는게 어떠할지에 대한 의견 부탁합니다.
=> Feature: 기수별 출석 목록 조회 기능 구현

src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
이슈링크(url): 
- Authentication이 유지하고 있던 값을 이메일에서 memberId로 변경한다.
=> Refactor: Authentication 인증 유지 값 변경

src/main/java/org/cotato/csquiz/api/socket/controller/SocketController.java, src/main/java/org/cotato/csquiz/api/socket/dto/EducationOpenRequest.java, src/main/java/org/cotato/csquiz/common/SchedulerService.java, src/main/java/org/cotato/csquiz/common/config/WebSocketConfig.java, src/main/java/org/cotato/csquiz/common/websocket/HandshakeInterceptor.java, src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java, src/main/java/org/cotato/csquiz/domain/education/repository/QuizRepository.java, src/main/java/org/cotato/csquiz/domain/education/service/EducationService.java, src/main/java/org/cotato/csquiz/domain/education/service/QuizSolveService.java, src/main/java/org/cotato/csquiz/domain/education/service/RecordService.java, src/main/java/org/cotato/csquiz/domain/education/service/SocketService.java
이슈링크(url): 
- 핸드쉐이크 파트 소켓 패키지로 옮김
-  소켓서비스 중 퀴즈 데이터 변경 부분을 퀴즈 풀이 서비스로 옮김
1차적으로 완료했는데 리펙토링 더 필요한 부분 찾고 있습니다
=> Refactor: 웹소켓 서비스 코드 분리

src/main/java/org/cotato/csquiz/api/project/controller/ProjectController.java, src/main/java/org/cotato/csquiz/api/project/dto/ProjectDetailResponse.java, src/main/java/org/cotato/csquiz/api/project/dto/ProjectImageInfoResponse.java, src/main/java/org/cotato/csquiz/api/project/dto/ProjectMemberInfoResponse.java, src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java, src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectImageRepository.java, src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectMemberRepository.java, src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectRepository.java, src/main/java/org/cotato/csquiz/domain/generation/service/ProjectService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/92#issue-2463166131
- 프로젝트 더보기 페이지에 반환할 정보
- 이름, 소개글, 깃허브 링크, 비헨스 링크, 프로젝트 링크, 기수, 사진 목록, 멤버 목록
=> Feature: 특정 프로젝트 상세 정보 반환 기능 구현

src/main/java/org/cotato/csquiz/common/S3/S3Uploader.java, src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java, src/main/java/org/cotato/csquiz/common/util/FileUtil.java
이슈링크(url): 
- S3Uploader 로그 단순화 및 파일 처리 개선
- 이미지 업로드 시 메타데이터 지정 작업 추가
마지막 커밋 제목 -> 파일 업로드 로그 단순화 및 파일 처리 개선
=> Refactor: 사진 업로드 메타데이터 지정 및 파일 처리 코드 개선

src/main/java/org/cotato/csquiz/common/S3/S3Uploader.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java
이슈링크(url): 
- convert 에러 -> IMAGE_CONVERT_FAIL 로 변경
- AmazonS3Exception 이 기존의 IMAGE_PROCESSING_FAIL 사용
- 확장자가 없을 때 예외 메세지 변경
=> Refactor: S3 예외 코드 분리 및 에러 메세지 변경

src/main/java/org/cotato/csquiz/api/project/dto/ProjectSummaryResponse.java
- ProjectSummaryResponse에 url 관련 정보 추가
=> Feature: 프로젝트 목록 반환 시 url 관련 정보 추가

src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java, src/main/java/org/cotato/csquiz/domain/generation/service/SessionService.java
이슈링크(url): 
- 세션 수정 시 출석 정보가 없을 때 처리
- 지각 마감 시간 오타 수정
=> Feature: 세션 수정 시 출석 정보가 없을 때 처리

src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/domain/generation/entity/Project.java, src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectImage.java, src/main/java/org/cotato/csquiz/domain/generation/entity/ProjectMember.java, src/main/java/org/cotato/csquiz/domain/generation/repository/ProjectImageRepository.java, src/main/java/org/cotato/csquiz/domain/generation/service/ProjectImageService.java
이슈링크(url): https://github.com/IT-Cotato/COTATO-BE/issues/156#issue-2533951853
- 프로젝트 추가 간에 검증 로직 및 예외 사항 핸들링 할 것
- extends로 BaseTimeEntity를 프로젝트, 프로젝트 이미지, 프로젝트 멤버에 달기
- order 0부터 시작하게 바꾸기
```SQL
UPDATE project_image pi
JOIN (
SELECT project_image_id,
ROW_NUMBER() OVER (PARTITION BY project_id ORDER BY project_image_id) - 1 AS new_order
FROM project_image
WHERE project_image_type = 'DETAIL' -- project_image_type를 지정
) AS ordered_images
ON pi.project_image_id = ordered_images.project_image_id
SET pi.project_image_order = ordered_images.new_order
WHERE pi.project_id = 1;  -- project_id를 지정
```
```SQL
ALTER TABLE Project
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE ProjectImage …
```
=> Fix: 기존에 등록된 프로젝트에 이미지 추가 시 예외처리 발생하지 않던 에러 해결

build.gradle, src/main/java/org/cotato/csquiz/common/config/JdaConfig.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/domain/education/cache/DiscordQuizRedisRepository.java, src/main/java/org/cotato/csquiz/domain/education/enums/QuizType.java, src/main/java/org/cotato/csquiz/domain/education/repository/ChoiceRepository.java, src/main/java/org/cotato/csquiz/domain/education/repository/EducationRepository.java, src/main/java/org/cotato/csquiz/domain/education/scheduler/QuizScheduler.java, src/main/java/org/cotato/csquiz/domain/education/service/ChoiceService.java, src/main/java/org/cotato/csquiz/domain/education/service/DiscordButtonListener.java, src/main/java/org/cotato/csquiz/domain/education/service/DiscordService.java, src/main/java/org/cotato/csquiz/domain/education/service/QuizService.java, src/main/java/org/cotato/csquiz/domain/education/service/dto/RandomQuizResponse.java, src/main/java/org/cotato/csquiz/domain/education/util/DiscordUtil.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
이슈링크(url): 
- Redis로 7일 이내에 전송된 문제는 제외를 했는데 이 부분에 대한 피드백 부탁드립니다.
- Discord bot과 Spring Application의 커넥션이 어플리케이션 시작 ~ 종료로 전체 시점인데 리소스가 괜찮을지에 대한 의견 궁금합니다.
=> Feature: 디스코드 봇을 활용한 1일 1 퀴즈 풀이 기능 구현

src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java, src/main/java/org/cotato/csquiz/api/generation/dto/GenerationInfoResponse.java, src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java
- 기수 단건 조회 기능 구현
- GenerationInfoResponse에 기수 시작 날짜와 끝 날짜추가
=> [COT-14]Feature: 기수 단건 조회 

src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
변경 이유: 기존에는 인증 시 헤더에 토큰을 넣고 memberId를 찾는 방식인데 `@AuthenticationPrincipal` 를 통해 간단하게 인증할 수 있는 방법을 찾음
이슈링크(url): 
- 헤더에 토큰을 넣는 방식에서 어노테이션으로 변경
=>  [COT-15] Refactor: 멤버 프로필 이미지 변경, 삭제 시 인증 방식 변경 

src/main/java/org/cotato/csquiz/common/email/EmailService.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/common/util/EmailUtil.java, src/main/java/org/cotato/csquiz/domain/auth/constant/EmailConstants.java, src/main/java/org/cotato/csquiz/domain/auth/service/AdminService.java, src/main/java/org/cotato/csquiz/domain/auth/service/EmailNotificationService.java, src/main/java/org/cotato/csquiz/domain/auth/service/EmailVerificationService.java
이슈링크(url): 
- 승인 완료, 거부, 재승인 시 이메일 전송
- OM 전환 시 이메일 전송
- OM 전환 시 List로 memberId를 받는데 받은 멤버 중 하나의 계정에서 문제가 생겨도 다 전환이 안되는 문제가 있을 것 같다.
=> [COT-13] Feature: OM 전환 및 가입 승인 시 이메일로 결과 전송

src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceStatistic.java, src/main/java/org/cotato/csquiz/domain/attendance/entity/AttendanceRecord.java
=> [COT-48] Fix: 관리자 기수별 출결 기록 조회 시 결석 정보 카운팅 문제 해결

src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java, src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceRecordController.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceTimeResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceWithSessionResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendancesResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/MemberAttendanceRecordsResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/UpdateAttendanceRecordRequest.java
- 출결 필드 API 필드명 통일
- 일부 클래스 records controller로 이동
=> [COT-88] Refactor: 출결 API 필드명 통일

src/main/java/org/cotato/csquiz/domain/education/embedded/Choices.java, src/main/java/org/cotato/csquiz/domain/education/entity/RandomQuiz.java, src/main/java/org/cotato/csquiz/domain/education/enums/QuizCategory.java
이슈링크(url): 
랜덤 퀴즈 테이블 생성
현재 퀴즈 카테고리 목록은 다음과 같은데 추가할만한 항목 있으면 말해주세요
```
NETWORK("네트워크"),
DB("데이터 베이스"),
OS("OS"),
OTHER("기타"),
```
```
CREATE TABLE random_quiz (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
created_at DATETIME(6) NULL,
modified_at DATETIME(6) NULL,
answer_number INT NOT NULL,
category SMALLINT NOT NULL,
choice1 VARCHAR(255) NOT NULL,
choice2 VARCHAR(255) NOT NULL,
choice3 VARCHAR(255) NOT NULL,
choice4 VARCHAR(255) NOT NULL,
file_name VARCHAR(255) NULL,
folder_name VARCHAR(255) NULL,
url VARCHAR(255) NULL,
question TEXT NOT NULL
);
```
=> [COT-111] Feature: 랜덤 퀴즈 테이블 생성

src/main/java/org/cotato/csquiz/api/quiz/controller/RandomQuizController.java, src/main/java/org/cotato/csquiz/api/quiz/dto/RandomTutorialQuizResponse.java, src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java, src/main/java/org/cotato/csquiz/domain/education/embedded/Choices.java, src/main/java/org/cotato/csquiz/domain/education/entity/RandomQuiz.java, src/main/java/org/cotato/csquiz/domain/education/repository/RandomQuizRepository.java, src/main/java/org/cotato/csquiz/domain/education/service/RandomQuizService.java, src/main/java/org/cotato/csquiz/domain/education/service/component/RandomQuizReader.java
이슈링크(url): 
develop 브랜치로 rebase하고 다시 브랜치 올렸습니다
=> [COT-112] Feature: 랜덤 퀴즈 반환 API 구현

src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceResponse.java, src/main/java/org/cotato/csquiz/api/attendance/dto/AttendanceWithSessionResponse.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceService.java
- 출석 단건 조회에 sessionType을 반환한다.
- 기수별 단건 조회엔 openStatus가 필요없다
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-123
=> [COT-123] Feature: 출석 단건 조회에 세션 타입 추가 및 기수별 목록 조회에 openStatus 제거

src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceRecordController.java, src/main/java/org/cotato/csquiz/api/auth/controller/AuthController.java, src/main/java/org/cotato/csquiz/api/education/controller/EducationController.java, src/main/java/org/cotato/csquiz/api/generation/controller/GenerationController.java, src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/api/mypage/controller/MyPageController.java, src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java, src/main/java/org/cotato/csquiz/api/policy/dto/FindMemberPolicyResponse.java, src/main/java/org/cotato/csquiz/api/session/dto/UpdateSessionRequest.java, src/main/java/org/cotato/csquiz/api/socket/controller/SocketController.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java, src/main/java/org/cotato/csquiz/common/config/jwt/JwtTokenProvider.java, src/main/java/org/cotato/csquiz/common/websocket/WebSocketHandler.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java, src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java, src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java, src/main/java/org/cotato/csquiz/domain/education/service/MyPageService.java, src/main/java/org/cotato/csquiz/domain/education/service/SocketService.java
필터에서 인증 시 SecurityContextHolder에 Member ID만 저장한다.
이로 인해 불필요하게 멤버 조회를 계속함
변경하자.
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=COT-121
너무 많아서 QA에서 테스트 진행
=> [COT-121] Feature: AuthPrincipal Context를 Member로 수정

src/main/java/org/cotato/csquiz/common/config/WebConfig.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/common/error/handler/GlobalExceptionHandler.java, src/main/java/org/cotato/csquiz/common/role/RoleAuthority.java, src/main/java/org/cotato/csquiz/common/role/RoleInterceptor.java, src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRole.java
현재 Security Config 파일을 통해 API 접근 권한을 관리하고 있다.
하지만 해당 방식은 아래와 같은 2가지 문제가 있다.
1. 파일이 매우 복잡하고 어지럽다.
2. 어플리케이션 로직이 변화에 따라 맞게 수정하기가 어렵다.
따라서, Controller에 어노테이션을 커스텀하고, 인터셉터에서 해당 역할과의 우선 순위를 비교해 처리한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-130&sprints=5
=> [COT-130] Feature: 어노테이션을 통한 권한에 따른 API 접근 설정

src/main/java/org/cotato/csquiz/api/record/controller/RecordController.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java, src/main/java/org/cotato/csquiz/domain/auth/component/GenerationMemberAuthValidator.java, src/main/java/org/cotato/csquiz/domain/auth/entity/Member.java, src/main/java/org/cotato/csquiz/domain/auth/enums/MemberRole.java, src/main/java/org/cotato/csquiz/domain/education/service/RecordService.java
OM이 Member 역할을 받게 되면서 OM이 사용하지 못하는 기능인 출결과 문제 풀이를 진행할 수 있다.
이에 대한 권한을 제한해야한다.
출결과 문제 풀이 액션을 하기 이전에 GenerationMember 테이블에 값이 있는지 확인한다.
단, 개발팀은 모든 역할에 접근이 가능해야하니 허용하는 AuthValidator를 추가한다.
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-136&sprints=5
=> [COT-136] Feature: DEV팀 역할 추가 및 권한 체크를 통한 활동 기수만 출결 + 문제 풀이 허용

src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
`@AuthenticationPrincipal` 로 필터에서 인증한 부원을 가져오면 이는 영속성 컨텍스트에 존재하지 않아 update를 해도 값이 반영되지 않는다.
명시적으로 save를 날려주자
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-153&sprints=9
=> [COT-153] Feature: 인증 필터의 Member를 명시적으로 저장한다

src/main/java/org/cotato/csquiz/common/config/auth/PrincipalDetails.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthenticationFilter.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
최초 회원가입한 유저가 로그인이 되지 않는다.
이유는 부원 역할 변경을 진행하며 member_role 필드를 null로 설정했는데 이게 PrincipalDetail getAuthorities 설정 시 에러를 발생함
원인은 member_role이 Null이기 때문
ROLE_역할이름 이 붙은 형태이면 무관하므로 ROLE_BASE로 기본 설정을 하자.
null로 설정 시 에러가 발생함.
다만, 이제 역할에 따른 세부 설정은 security 에서 진행하지 않는데, Security 기반 로그인이 필요할까 싶다.
하지만, 하위호환성을 고려해 일단은 skip..
resolve: https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-160&sprints=13
=> [COT-160] Hotfix: 회원가입한 부원이 로그인 되지 않는 이슈

build.gradle, src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/api/member/dto/AddableMemberInfo.java, src/main/java/org/cotato/csquiz/api/member/dto/AddableMembersResponse.java, src/main/java/org/cotato/csquiz/common/config/JpaConfig.java, src/main/java/org/cotato/csquiz/domain/auth/entity/Member.java, src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepository.java, src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepositoryCustom.java, src/main/java/org/cotato/csquiz/domain/auth/repository/MemberRepositoryCustomImpl.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java, src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationMemberRepository.java
기수별 부원 목록 추가 시 가능한 멤버 목록을 반환하는 API를 통해 등록 가능한 멤버 리스트를 반환한다.
필터링하는 기준은 다음과 같다.
- 해당 기수에 이미 들어가 있는 멤버는 제외(필수)
- OM과 활동 부원(필수)
- 기수(선택)
- 포지션(선택)
- 이름(선택)
각 필터를 적용하는 방법을 다음과 같다.
- OM과 활동 부원(필수)
- MemberStatus.java에 해당 부분이 있다.
```
REJECTED("가입 신청 후 거절된 부원"),
REQUESTED("최초 가입 신청한 대기 상태의 부원"),
RETIRED("수료 후 활동을 종료한 부원"),
APPROVED("가입 신청 후 승인된 부원")
;
```
RETIRED와 APPROVED 항목을 가져온다. 
- 해당 기수에 이미 들어가 있는 멤버는 제외(필수)
- 기수(generationId) 를 param으로 받아 generationMember의 memberId 리스트를 만든다.
- 활동 + OM 멤버의 memberId가 리스트 존재한다면 거른다
- 기수, 포지션, 이름(선택)
- QueryDsl을 통해 동적으로 필터링한다.
- 활동 부원(MemberStatus.APPROVED)가 먼저 나오고 OM이 나온다.
- 이후 이름 순으로 정렬
https://youthing.atlassian.net/jira/software/projects/COT/boards/2/backlog?selectedIssue=COT-156
=> [COT-156] Feature: GenerationMember에 추가 가능한 멤버 리스트 반환 API

src/main/java/org/cotato/csquiz/api/policy/controller/PolicyController.java, src/main/java/org/cotato/csquiz/domain/auth/entity/Policy.java, src/main/java/org/cotato/csquiz/domain/auth/enums/PolicyCategory.java, src/main/java/org/cotato/csquiz/domain/auth/repository/PolicyRepository.java, src/main/java/org/cotato/csquiz/domain/auth/service/PolicyService.java
회원 탈퇴 정책 조회 API를 구현한다.
이 때, 기존 정책과 구분이 필요하다.
현재 정책은 회원 가입 시에 조회하는 '개인 정보 보호' 정책이다.
'탈퇴' 관련 정책을 추가하자.
resolve: https://youthing.atlassian.net/browse/COT-166
```SQL
ALTER TABLE policy
ADD COLUMN category VARCHAR(255) NOT NULL;
update policy set category = 'PERSONAL_INFORMATION' where policy_id in (1, 2);
```
=> [COT-166] Feature: 회원 탈퇴 정책 조회 API 구현

src/main/java/org/cotato/csquiz/api/member/dto/GenerationMemberInfo.java, src/main/java/org/cotato/csquiz/api/member/dto/UpdateGenerationMemberRoleRequest.java, src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java, src/main/java/org/cotato/csquiz/domain/generation/entity/GenerationMember.java, src/main/java/org/cotato/csquiz/domain/generation/enums/GenerationMemberRole.java
MemberRole enum 값이 변경됨에 따라 기수별 멤버 목록에 사용될 Enum 값이 추가되어야 한다.
기존 MemberRole에서 GenerationMemberRole로 타입을 변경함
기존과 컬럼명이 동일하기 때문에 임시 컬럼을 만들고 이전할 예정
```SQL
UPDATE generation_member 
SET role = 'LEADER_TEAM' where role = 'ADMIN';
UPDATE generation_member 
SET role = 'EDUCATION_TEAM' where role = 'EDUCUATION';
**이 때 기존에 팀장들은 ADMIN이기 때문에 수동으로 각 팀으로 변경해줘야한다.**
```
=> [COT-168] Feature: 기수별 멤버 역할 필드 타입 변경

src/main/java/org/cotato/csquiz/api/session/controller/SessionController.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java
교육과 연결된 세션 목록은 교육 추가 시에만 필요한 API라 Manager 권한이 부여됨
하지만, session 이하 GET 메서드는 인증을 진행하지 않음
- 모두에게 허용하자.
- 추후에 교육과 세션 연결 해제 시 삭제될 API임
=> [COT-176] Hotfix: 교육과 연결된 세션 목록 접근 권한 해제

src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/api/member/dto/MemberMyPageInfoResponse.java, src/main/java/org/cotato/csquiz/api/member/dto/ProfileInfoResponse.java, src/main/java/org/cotato/csquiz/api/member/dto/ProfileLinkResponse.java, src/main/java/org/cotato/csquiz/domain/auth/repository/ProfileLinkRepository.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java
- 프로필 카드 정보를 가져올 수 없어 API 구현
- 프로필 카드에 필요한 정보를 반환하는 API 구현
- 마이페이지 정보 반환 시 프로필 사진 정보는 반환하지 않게 변경
고민한 사항
- 프로필 카드는 마이페이지에서만 보여지는 것이 아닌 다양한 곳에 사용될 예정
- 이로 인해 프로필 카드 정보만 가져와야 할 상황이 존재해 마이페이지의 정보를 반환하는 API와는 분리된 API가 있어야 한다 판단
- `AuthenticationPrincipal`이 아닌 memberId를 기반으로 반환해 다른 멤버의 프로필 정보도 확인할 수 있게 작업
https://youthing.atlassian.net/browse/COT-187
=> [COT-187] Feature: 프로필 정보 반환 API

src/main/java/org/cotato/csquiz/api/event/controller/EventController.java, src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java, src/main/java/org/cotato/csquiz/common/sse/SseAttendanceRepository.java, src/main/java/org/cotato/csquiz/common/sse/SseSender.java, src/main/java/org/cotato/csquiz/common/sse/SseService.java, src/main/java/org/cotato/csquiz/domain/attendance/service/component/AttendanceReader.java, src/main/java/org/cotato/csquiz/domain/generation/repository/SessionRepository.java, src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java
현재 활동 기수의 부원이 로그인 하면 출결 알림에 따른 이벤트 구독 요청을 한다.
1. 현재 기수 여부 확인 (현재 기수가 아니라면 예외 처리)
2. 오늘 날짜의 세션이 존재하지 않는 경우 -> 출결이 없음 (CLOSED)
3. 오늘 날짜의 세션이 있지만 NO_ATTEND인 경우 -> CLOSED
4. 오늘 출석이 존재 -> 현재 Open 상태 + attendanceId 전송
구체적인 내용은 아래 노션 문서 확인
https://www.notion.so/youthhing/Server-Tech-Doc-19787d592b6e80f398cdd25b00b9278d?pvs=4
sse emitter 를 활용해 구현한다.
서버 메모리가 고려되긴 하지만 활동 기수는 최대 40명이내이기에 우선 진행 후 모니터링한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?sprints=11
=> [COT-209] Feature: 최초 로그인 시 출결 이벤트 구독 API

src/main/java/org/cotato/csquiz/domain/generation/entity/Generation.java, src/main/java/org/cotato/csquiz/domain/generation/repository/GenerationRepository.java, src/main/java/org/cotato/csquiz/domain/generation/service/GenerationService.java, src/main/java/org/cotato/csquiz/domain/generation/service/component/GenerationReader.java, src/test/java/org/cotato/csquiz/domain/generation/service/GenerationServiceTest.java
기수 목록 조회 시 4 ~ 7기가 노출된다.
기수 노출 여부 필드를 추가하고 기수 조회 시 generationReader를 활용하자
```sql
alter table generation add column visible bit
update generation set visible = 1 where generation_id in (5,6,7,8);
=> [COT-243] Feature: 기수 노출 필드 추가

src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java, src/test/java/org/cotato/csquiz/domain/auth/service/MemberServiceTest.java
부원 이름을 노출할 때 정렬 기준이 없다.
1. 부원 목록 조회 시 기수 내림차순
2. 이름 오름차순으로 정렬하자.
=> [COT-239] Feature: 부원 이름 노출 시 정렬

src/main/java/org/cotato/csquiz/api/attendance/controller/AttendanceController.java, src/main/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordService.java, src/main/java/org/cotato/csquiz/domain/attendance/service/component/AttendanceRecordReader.java, src/main/java/org/cotato/csquiz/domain/generation/enums/SessionType.java, src/main/java/org/cotato/csquiz/domain/generation/service/component/SessionReader.java, src/test/java/org/cotato/csquiz/domain/attendance/service/AttendanceRecordServiceTest.java
관리자가 출결 기록을 업데이트하는 과정에서 에러가 발생한다.
업데이트 하는 경우 세션 타입에 맞는 출석 결과 확인 시 attendance_type과 session_type을 비교해서 문제가 발생 중
attendance_type과의 비교가 아닌 바꾸려는 결과 'attendance_result'와 비교하자.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-253&sprints=13
=> [COT-253] Hotfix: 출결 기록 변경 시 세션 타입과 변경할 결과 비교 로직 에러 해결

src/main/java/org/cotato/csquiz/api/auth/dto/JoinRequest.java, src/main/java/org/cotato/csquiz/api/member/dto/UpdatePasswordRequest.java, src/main/java/org/cotato/csquiz/common/validator/Password.java, src/main/java/org/cotato/csquiz/common/validator/PasswordValidator.java, src/main/java/org/cotato/csquiz/common/validator/Phone.java, src/main/java/org/cotato/csquiz/common/validator/PhoneValidator.java, src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java, src/main/java/org/cotato/csquiz/domain/auth/service/MemberService.java, src/main/java/org/cotato/csquiz/domain/auth/service/ValidateService.java
기존 전화번호와 비밀번호는 서비스 로직 내부에서 검증을 진행했다.
하지만 이는 사용자 입력 값을 검증하는 것으로 서비스 로직 내부에서 검증을 제외하고 싶다.
어노테이션을 활용해 검증 위치를 앞으로 당긴다.
validation 패키지를 활용한다.
단, 기존 프론트엔드 개발자의 요구사항으로 인해 전화번호 검증 로직 같은 경우엔 010으로 시작하지 않는 경우와 11자리 숫자가 아닌 경우를 모두 포함해야하므로 AppException을 내려준다. (추후 논의 후 수정 가능)
✅ 논의 후 MethodArgumentException으로 처리하기로 결정
=> [COT-269] Refactor: 전화번호 및 비밀번호 검증 어노테이션 구현

src/main/java/org/cotato/csquiz/common/config/JdaConfig.java, src/main/java/org/cotato/csquiz/domain/education/repository/QuizRepository.java, src/main/java/org/cotato/csquiz/domain/education/scheduler/QuizScheduler.java, src/main/java/org/cotato/csquiz/domain/education/service/QuizService.java, src/main/java/org/cotato/csquiz/domain/education/service/component/DiscordButtonListener.java, src/main/java/org/cotato/csquiz/domain/education/service/component/DiscordConnector.java, src/main/java/org/cotato/csquiz/domain/education/service/component/EducationReader.java, src/main/java/org/cotato/csquiz/domain/education/service/component/QuizReader.java, src/test/java/org/cotato/csquiz/domain/education/service/component/QuizReaderTest.java
현재 디스코드에 2시마다 퀴즈가 전송되는 상황에서 퀴즈 문제의 길이가 80을 넘어가면 에러로 인해 아무 문제도 전송되지 않는다.
이는 JDA 설정에 따른 문제이다.
길이가 80이하인 문제만 조회 후 전송한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-270&sprints=9
=> [COT-270] Feature: 디스코드 랜덤 문제 전송 실패 방지 처리

src/main/java/org/cotato/csquiz/api/recruitment/controller/RecruitmentController.java, src/main/java/org/cotato/csquiz/api/recruitment/dto/RequestRecruitmentNotificationRequest.java, src/main/java/org/cotato/csquiz/common/config/SecurityConfig.java, src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthorizationFilter.java, src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/domain/recruitment/entity/RecruitmentNotificationRequester.java, src/main/java/org/cotato/csquiz/domain/recruitment/repository/RecruitmentNotificationRequesterRepository.java, src/main/java/org/cotato/csquiz/domain/recruitment/service/RecruitmentNotificationService.java, src/main/java/org/cotato/csquiz/domain/recruitment/service/component/RecruitmentNotificationRequesterReader.java, src/test/java/org/cotato/csquiz/domain/recruitment/service/RecruitmentNotificationServiceTest.java
해당 PR은 [COT-342](https://github.com/IT-Cotato/COTATO-BE/pull/342) 커밋이 포함되어 있음
모집 알람 신청 시 저장하는 API
구현
https://youthing.atlassian.net/browse/COT-263
테스트 코드 참고
Enum 컬럼 String 설정
```sql
ALTER TABLE recruitment_notification_requester
MODIFY COLUMN send_status VARCHAR(255) NOT NULL;
```
=> [COT-263] Feature: 모집 알림 신청 API 구현

src/main/java/org/cotato/csquiz/common/config/filter/JwtAuthenticationFilter.java, src/main/java/org/cotato/csquiz/common/config/jwt/JwtTokenProvider.java, src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java, src/main/java/org/cotato/csquiz/domain/auth/service/component/MemberReader.java, src/test/java/org/cotato/csquiz/common/config/jwt/JwtTokenProviderTest.java
Spring Security에서 authority 기반으로 API 권한 체크를 하지 않기에 더이상 토큰에 role을 담을 필요가 없음
또한 추후에 필요가 있더라도, id기준으로 조회 후 `member.getRole()`기준으로 추가하면 되기에 토큰 자체에 role 이 필요가 없음.
제거한다.
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-271&sprints=9
- admin 권한 api 테스트 진행 완료
=> [COT-271] Feature: JWT에서 role 필드를 제거

src/main/java/org/cotato/csquiz/api/member/controller/GenerationMemberController.java, src/main/java/org/cotato/csquiz/api/member/dto/UpdateGenerationMemberRoleRequest.java, src/main/java/org/cotato/csquiz/domain/auth/service/GenerationMemberService.java, src/test/java/org/cotato/csquiz/domain/auth/service/GenerationMemberServiceTest.java
기수별 활동 부원 API 경로가 restful하지 않다.
부원 역할 수정
기존 : PATCH /v2/api/generation-members
아래와 같이 수정한다.
PATCH /v2/api/generation-members/{generationMemberId}/role
https://youthing.atlassian.net/jira/software/projects/COT/boards/2?selectedIssue=COT-280&sprints=9
=> [COT-280] Refactor: 기수별 활동 부원 API 경로 수정

src/main/java/org/cotato/csquiz/api/member/controller/MemberController.java, src/main/java/org/cotato/csquiz/common/response/PageResponse.java
현재 페이징을 활용하는 API(OM 검색 및 회원 상태에 따른 조회)에는 필요 이상의 필드가 반환되고 있다.
예시
```json
{
"totalPages": 0,
"totalElements": 0,
"size": 0,
"content": [
{
"memberId": 0,
"name": "string",
"backFourNumber": "string",
"role": "MEMBER",
"position": "NONE",
"status": "INACTIVE",
"passedGenerationNumber": 0
}
],
"number": 0,
"sort": {
"empty": true,
"sorted": true,
"unsorted": true
},
"numberOfElements": 0,
"pageable": {
"offset": 0,
"sort": {
"empty": true,
"sorted": true,
"unsorted": true
},
"pageSize": 0,
"pageNumber": 0,
"unpaged": true,
"paged": true
},
"first": true,
"last": true,
"empty": true
}
```
필요한 필드만 남긴다.
https://youthing.atlassian.net/browse/COT-279
=> [COT-279] Feature: PageResponse로 페이징 시 필요한 필드만 반환한다.

src/main/java/org/cotato/csquiz/common/error/ErrorCode.java, src/main/java/org/cotato/csquiz/common/event/CotatoEvent.java, src/main/java/org/cotato/csquiz/common/event/CotatoEventListener.java, src/main/java/org/cotato/csquiz/common/event/CotatoEventPublisher.java, src/main/java/org/cotato/csquiz/common/event/EmailSendEvent.java, src/main/java/org/cotato/csquiz/common/event/EventType.java, src/main/java/org/cotato/csquiz/domain/auth/service/AdminMemberService.java, src/main/java/org/cotato/csquiz/domain/auth/service/AuthService.java, src/test/java/org/cotato/csquiz/common/event/CotatoEventListenerTest.java, src/test/java/org/cotato/csquiz/common/event/CotatoEventPublisherTest.java, src/test/java/org/cotato/csquiz/domain/auth/service/AdminMemberServiceTest.java
현재 부원 가입 승인/거절 요청 시 외부 API를 호출하는 로직이 포함되어있다.
클래스가 분리되어있지만 Service 클래스 간의 결합도가 높아지는 상황
이는 하나의 메서드에 책임을 과도화 하게 된다.
이벤트를 발행해서 메서드의 책임을 낮춘다.
=> [COT-274] Feature: 부원 가입 승인/거절 시 이메일 발송 이벤트 처리
